// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TociCodeBooster
{
    internal sealed partial class Vsix
    {
        public const string Id = "TociCodeBooster.67b44461-7f56-486d-9256-f873b71847f7";
        public const string Name = "TociCodeBooster";
        public const string Description = @"Code booster by Toci";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "HP";
        public const string Tags = "";
    }
}
