// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Toci.PlotTwist.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TociCodeBoosterString = "57ce0dc6-35b4-4145-801a-1295206a9988";
        public static Guid TociCodeBooster = new Guid(TociCodeBoosterString);

        public const string guidTociCodeBoosterPackageCmdSetString = "22d887a7-d5c7-43e7-87dd-6c906639eb80";
        public static Guid guidTociCodeBoosterPackageCmdSet = new Guid(guidTociCodeBoosterPackageCmdSetString);

        public const string guidImagesString = "a3239830-b200-4830-b869-bb6cfa0b2996";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int cmdidAddCommonsReference = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}